export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const LOADED_PRODUCTS = "LOADED_PRODUCTS";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
